"""phase 3a3.1 schedule version persistence schema

Revision ID: 4681f7a362bd
Revises: 8cdd513e16da
Create Date: 2026-09-05 18:35:34.817365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4681f7a362bd'
down_revision: Union[str, Sequence[str], None] = '8cdd513e16da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('active_version_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_schedule_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'id', name='uq_schedule_ay_id'),
    sa.UniqueConstraint('academic_year_id', name='uq_schedule_academic_year_id')
    )
    op.create_table('schedule_version',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.BigInteger(), nullable=True),
    sa.Column('solver_status', sa.Text(), nullable=False),
    sa.Column('total_soft_penalty', sa.Integer(), nullable=False),
    sa.Column('wall_time_seconds', sa.Double(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("solver_status IN ('OPTIMAL', 'FEASIBLE')", name='ck_schedule_version_solver_status'),
    sa.ForeignKeyConstraint(['academic_year_id', 'schedule_id'], ['schedule.academic_year_id', 'schedule.id'], name='fk_schedule_version_schedule', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_schedule_version_academic_year', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id', 'parent_version_id'], ['schedule_version.schedule_id', 'schedule_version.id'], name='fk_schedule_version_parent'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'id', name='uq_schedule_version_ay_id'),
    sa.UniqueConstraint('schedule_id', 'id', name='uq_schedule_version_schedule_id'),
    sa.UniqueConstraint('schedule_id', 'version_number', name='uq_schedule_version_schedule_version_number')
    )
    # Manual correction: `schedule.active_version_id -> schedule_version`
    # and `schedule_version.schedule_id -> schedule` form a genuine
    # two-table FK cycle. `op.create_table()` does not automatically defer
    # `use_alter=True` constraints the way `MetaData.create_all()` does --
    # verified directly against real PostgreSQL: autogenerate silently
    # omitted this constraint from the rendered `CREATE TABLE schedule`
    # statement and never added it elsewhere. Adding it explicitly here,
    # now that both tables exist, closes that gap.
    op.create_foreign_key(
        'fk_schedule_active_version', 'schedule', 'schedule_version',
        ['id', 'active_version_id'], ['schedule_id', 'id'],
    )
    op.create_table('locked_occurrence',
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_version_id', sa.BigInteger(), nullable=False),
    sa.Column('teaching_requirement_id', sa.BigInteger(), nullable=False),
    sa.Column('day_id', sa.BigInteger(), nullable=False),
    sa.Column('anchor_period_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id', 'anchor_period_id'], ['period.academic_year_id', 'period.id'], name='fk_locked_occurrence_anchor_period', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'day_id'], ['day.academic_year_id', 'day.id'], name='fk_locked_occurrence_day', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'schedule_version_id'], ['schedule_version.academic_year_id', 'schedule_version.id'], name='fk_locked_occurrence_schedule_version', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['academic_year_id', 'teaching_requirement_id'], ['teaching_requirement.academic_year_id', 'teaching_requirement.id'], name='fk_locked_occurrence_teaching_requirement', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_locked_occurrence_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_version_id', 'teaching_requirement_id', 'day_id', 'anchor_period_id', name='pk_locked_occurrence')
    )
    op.create_table('schedule_entry',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_version_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('day_id', sa.BigInteger(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('teaching_requirement_id', sa.BigInteger(), nullable=True),
    sa.Column('reserved_block_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("(source = 'REQUIREMENT') = (teaching_requirement_id IS NOT NULL) AND (source = 'RESERVED_BLOCK') = (reserved_block_id IS NOT NULL)", name='ck_schedule_entry_source_reference'),
    sa.CheckConstraint("source IN ('REQUIREMENT', 'RESERVED_BLOCK')", name='ck_schedule_entry_source'),
    sa.ForeignKeyConstraint(['academic_year_id', 'day_id'], ['day.academic_year_id', 'day.id'], name='fk_schedule_entry_day', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'period_id'], ['period.academic_year_id', 'period.id'], name='fk_schedule_entry_period', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'reserved_block_id'], ['reserved_block.academic_year_id', 'reserved_block.id'], name='fk_schedule_entry_reserved_block', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'schedule_version_id'], ['schedule_version.academic_year_id', 'schedule_version.id'], name='fk_schedule_entry_schedule_version', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['academic_year_id', 'teaching_requirement_id'], ['teaching_requirement.academic_year_id', 'teaching_requirement.id'], name='fk_schedule_entry_teaching_requirement', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_schedule_entry_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_version_id', 'ordinal', name='uq_schedule_entry_version_ordinal')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_entry')
    op.drop_table('locked_occurrence')
    # Manual correction: drop the cyclic FK before either table it spans
    # is dropped.
    op.drop_constraint('fk_schedule_active_version', 'schedule', type_='foreignkey')
    op.drop_table('schedule_version')
    op.drop_table('schedule')
    # ### end Alembic commands ###
