"""phase 3a2.1 persisted scheduling configuration schema

Revision ID: 8cdd513e16da
Revises: e2cbe4786a14
Create Date: 2026-09-05 09:15:07.761097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cdd513e16da'
down_revision: Union[str, Sequence[str], None] = 'e2cbe4786a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('natural_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('natural_id', name='uq_school_natural_id')
    )
    op.create_table('academic_year',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('natural_id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name='fk_academic_year_school', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'natural_id', name='uq_academic_year_school_natural_id')
    )
    op.create_table('activity',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('natural_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), server_default='ORDINARY', nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("kind IN ('ORDINARY', 'CLUB')", name='ck_activity_kind'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_activity_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'id', name='uq_activity_ay_id'),
    sa.UniqueConstraint('academic_year_id', 'natural_id', name='uq_activity_ay_natural_id'),
    sa.UniqueConstraint('academic_year_id', 'ordinal', name='uq_activity_ay_ordinal')
    )
    op.create_table('class_section',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('natural_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_class_section_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'id', name='uq_class_section_ay_id'),
    sa.UniqueConstraint('academic_year_id', 'natural_id', name='uq_class_section_ay_natural_id'),
    sa.UniqueConstraint('academic_year_id', 'ordinal', name='uq_class_section_ay_ordinal')
    )
    op.create_table('day',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('natural_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('idx', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_day_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'id', name='uq_day_ay_id'),
    sa.UniqueConstraint('academic_year_id', 'idx', name='uq_day_ay_idx'),
    sa.UniqueConstraint('academic_year_id', 'natural_id', name='uq_day_ay_natural_id')
    )
    op.create_table('participant_group',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('natural_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_participant_group_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'id', name='uq_participant_group_ay_id'),
    sa.UniqueConstraint('academic_year_id', 'natural_id', name='uq_participant_group_ay_natural_id'),
    sa.UniqueConstraint('academic_year_id', 'ordinal', name='uq_participant_group_ay_ordinal')
    )
    op.create_table('period',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('natural_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('idx', sa.SmallInteger(), nullable=False),
    sa.Column('block_id', sa.Text(), nullable=False),
    sa.Column('is_instructional', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_period_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'id', name='uq_period_ay_id'),
    sa.UniqueConstraint('academic_year_id', 'idx', name='uq_period_ay_idx'),
    sa.UniqueConstraint('academic_year_id', 'natural_id', name='uq_period_ay_natural_id')
    )
    op.create_index('ix_period_ay_block', 'period', ['academic_year_id', 'block_id'], unique=False)
    op.create_table('resource',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('natural_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('capacity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_resource_capacity_positive'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_resource_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'id', name='uq_resource_ay_id'),
    sa.UniqueConstraint('academic_year_id', 'natural_id', name='uq_resource_ay_natural_id'),
    sa.UniqueConstraint('academic_year_id', 'ordinal', name='uq_resource_ay_ordinal')
    )
    op.create_table('teacher',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('natural_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_teacher_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'id', name='uq_teacher_ay_id'),
    sa.UniqueConstraint('academic_year_id', 'natural_id', name='uq_teacher_ay_natural_id'),
    sa.UniqueConstraint('academic_year_id', 'ordinal', name='uq_teacher_ay_ordinal')
    )
    op.create_table('participant_group_class_section',
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('participant_group_id', sa.BigInteger(), nullable=False),
    sa.Column('class_section_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id', 'class_section_id'], ['class_section.academic_year_id', 'class_section.id'], name='fk_pgcs_class_section', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'participant_group_id'], ['participant_group.academic_year_id', 'participant_group.id'], name='fk_pgcs_participant_group', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_pgcs_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('participant_group_id', 'ordinal', name='pk_participant_group_class_section'),
    sa.UniqueConstraint('participant_group_id', 'class_section_id', name='uq_pgcs_group_class')
    )
    op.create_table('reserved_block',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('natural_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=True),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id', 'activity_id'], ['activity.academic_year_id', 'activity.id'], name='fk_reserved_block_activity', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'teacher_id'], ['teacher.academic_year_id', 'teacher.id'], name='fk_reserved_block_teacher', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_reserved_block_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'id', name='uq_reserved_block_ay_id'),
    sa.UniqueConstraint('academic_year_id', 'natural_id', name='uq_reserved_block_ay_natural_id'),
    sa.UniqueConstraint('academic_year_id', 'ordinal', name='uq_reserved_block_ay_ordinal')
    )
    op.create_table('teacher_availability',
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('day_id', sa.BigInteger(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("status IN ('AVAILABLE', 'PREFER_NOT', 'UNAVAILABLE')", name='ck_teacher_availability_status'),
    sa.ForeignKeyConstraint(['academic_year_id', 'day_id'], ['day.academic_year_id', 'day.id'], name='fk_teacher_availability_day', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'period_id'], ['period.academic_year_id', 'period.id'], name='fk_teacher_availability_period', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'teacher_id'], ['teacher.academic_year_id', 'teacher.id'], name='fk_teacher_availability_teacher', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_teacher_availability_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'day_id', 'period_id', name='pk_teacher_availability'),
    sa.UniqueConstraint('academic_year_id', 'ordinal', name='uq_teacher_availability_ay_ordinal')
    )
    op.create_index('ix_teacher_availability_teacher', 'teacher_availability', ['teacher_id'], unique=False)
    op.create_table('teaching_requirement',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('natural_id', sa.Text(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('participant_group_id', sa.BigInteger(), nullable=False),
    sa.Column('weekly_periods', sa.Integer(), nullable=False),
    sa.Column('block_mode', sa.Text(), server_default='FLEXIBLE', nullable=False),
    sa.Column('block_sizes', postgresql.ARRAY(sa.SmallInteger()), server_default='{}', nullable=False),
    sa.Column('min_distinct_days', sa.SmallInteger(), nullable=True),
    sa.Column('max_periods_per_day', sa.SmallInteger(), nullable=True),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('split_group_id', sa.Text(), nullable=True),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("block_mode IN ('REQUIRED', 'PREFERRED', 'FLEXIBLE')", name='ck_teaching_requirement_block_mode'),
    sa.CheckConstraint('weekly_periods > 0', name='ck_teaching_requirement_weekly_periods_positive'),
    sa.ForeignKeyConstraint(['academic_year_id', 'activity_id'], ['activity.academic_year_id', 'activity.id'], name='fk_teaching_requirement_activity', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'participant_group_id'], ['participant_group.academic_year_id', 'participant_group.id'], name='fk_teaching_requirement_participant_group', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'resource_id'], ['resource.academic_year_id', 'resource.id'], name='fk_teaching_requirement_resource', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'teacher_id'], ['teacher.academic_year_id', 'teacher.id'], name='fk_teaching_requirement_teacher', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_teaching_requirement_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'id', name='uq_teaching_requirement_ay_id'),
    sa.UniqueConstraint('academic_year_id', 'natural_id', name='uq_teaching_requirement_ay_natural_id'),
    sa.UniqueConstraint('academic_year_id', 'ordinal', name='uq_teaching_requirement_ay_ordinal')
    )
    op.create_index('ix_teaching_requirement_ay_participant_group', 'teaching_requirement', ['academic_year_id', 'participant_group_id'], unique=False)
    op.create_index('ix_teaching_requirement_ay_split_group', 'teaching_requirement', ['academic_year_id', 'split_group_id'], unique=False, postgresql_where=sa.text('split_group_id IS NOT NULL'))
    op.create_index('ix_teaching_requirement_ay_teacher', 'teaching_requirement', ['academic_year_id', 'teacher_id'], unique=False)
    op.create_table('fixed_placement',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('natural_id', sa.Text(), nullable=False),
    sa.Column('teaching_requirement_id', sa.BigInteger(), nullable=False),
    sa.Column('day_id', sa.BigInteger(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id', 'day_id'], ['day.academic_year_id', 'day.id'], name='fk_fixed_placement_day', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'period_id'], ['period.academic_year_id', 'period.id'], name='fk_fixed_placement_period', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'teaching_requirement_id'], ['teaching_requirement.academic_year_id', 'teaching_requirement.id'], name='fk_fixed_placement_teaching_requirement', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_fixed_placement_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'natural_id', name='uq_fixed_placement_ay_natural_id'),
    sa.UniqueConstraint('academic_year_id', 'ordinal', name='uq_fixed_placement_ay_ordinal')
    )
    op.create_index('ix_fixed_placement_teaching_requirement', 'fixed_placement', ['teaching_requirement_id'], unique=False)
    op.create_table('reserved_block_class_section',
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('reserved_block_id', sa.BigInteger(), nullable=False),
    sa.Column('class_section_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id', 'class_section_id'], ['class_section.academic_year_id', 'class_section.id'], name='fk_rbcs_class_section', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'reserved_block_id'], ['reserved_block.academic_year_id', 'reserved_block.id'], name='fk_rbcs_reserved_block', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_rbcs_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reserved_block_id', 'ordinal', name='pk_reserved_block_class_section'),
    sa.UniqueConstraint('reserved_block_id', 'class_section_id', name='uq_rbcs_block_class')
    )
    op.create_table('reserved_block_slot',
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('reserved_block_id', sa.BigInteger(), nullable=False),
    sa.Column('day_id', sa.BigInteger(), nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id', 'day_id'], ['day.academic_year_id', 'day.id'], name='fk_rbs_day', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'period_id'], ['period.academic_year_id', 'period.id'], name='fk_rbs_period', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['academic_year_id', 'reserved_block_id'], ['reserved_block.academic_year_id', 'reserved_block.id'], name='fk_rbs_reserved_block', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_rbs_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reserved_block_id', 'ordinal', name='pk_reserved_block_slot'),
    sa.UniqueConstraint('reserved_block_id', 'day_id', 'period_id', name='uq_rbs_block_day_period')
    )
    op.create_table('time_preference',
    sa.Column('academic_year_id', sa.BigInteger(), nullable=False),
    sa.Column('teaching_requirement_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('preferred_period_indexes', postgresql.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('weight', sa.Text(), server_default='MEDIUM', nullable=False),
    sa.CheckConstraint("weight IN ('LOW', 'MEDIUM', 'HIGH')", name='ck_time_preference_weight'),
    sa.ForeignKeyConstraint(['academic_year_id', 'teaching_requirement_id'], ['teaching_requirement.academic_year_id', 'teaching_requirement.id'], name='fk_time_preference_teaching_requirement', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name='fk_time_preference_academic_year', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teaching_requirement_id', 'ordinal', name='pk_time_preference')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_preference')
    op.drop_table('reserved_block_slot')
    op.drop_table('reserved_block_class_section')
    op.drop_index('ix_fixed_placement_teaching_requirement', table_name='fixed_placement')
    op.drop_table('fixed_placement')
    op.drop_index('ix_teaching_requirement_ay_teacher', table_name='teaching_requirement')
    op.drop_index('ix_teaching_requirement_ay_split_group', table_name='teaching_requirement', postgresql_where=sa.text('split_group_id IS NOT NULL'))
    op.drop_index('ix_teaching_requirement_ay_participant_group', table_name='teaching_requirement')
    op.drop_table('teaching_requirement')
    op.drop_index('ix_teacher_availability_teacher', table_name='teacher_availability')
    op.drop_table('teacher_availability')
    op.drop_table('reserved_block')
    op.drop_table('participant_group_class_section')
    op.drop_table('teacher')
    op.drop_table('resource')
    op.drop_index('ix_period_ay_block', table_name='period')
    op.drop_table('period')
    op.drop_table('participant_group')
    op.drop_table('day')
    op.drop_table('class_section')
    op.drop_table('activity')
    op.drop_table('academic_year')
    op.drop_table('school')
    # ### end Alembic commands ###
