"""add reserved_block resource_id

Revision ID: 9fbec2126831
Revises: cae76cba3c58
Create Date: 2026-09-10 22:25:34.725638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbec2126831'
down_revision: Union[str, Sequence[str], None] = 'cae76cba3c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserved_block', sa.Column('resource_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_reserved_block_resource', 'reserved_block', 'resource', ['academic_year_id', 'resource_id'], ['academic_year_id', 'id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_reserved_block_resource', 'reserved_block', type_='foreignkey')
    op.drop_column('reserved_block', 'resource_id')
    # ### end Alembic commands ###
